export const HOTEL_NAME = 'HOTEL_NAME';
export const UPDATE_NAMEADDRESS = 'UPDATE_NAMEADDRESS';
export const BILLING_ADDRESS = 'BILLING_ADDRESS';
export const LEGAL_ADDRESS = 'LEGAL_ADDRESS';
export const DESCRIPTION = 'DESCRIPTION';
export const AMENITIES = 'AMENITIES';
export const IMAGES = 'IMAGES';
